name: Cargo build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0
      - run: cargo test -- --include-ignored
      - run: cargo test --examples
      - run: cargo doc --no-deps
      - run: cargo bench --no-run --profile dev
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo-criterion
      - run: cargo criterion